[local]
localhost

[mongodb]
mongodb.daws90s.uk

[redis]
redis.daws90s.uk

[mysql]
mysql.daws90s.uk

[rabbitmq]
rabbitmq.daws90s.uk

[catalogue]
catalogue.daws90s.uk

[user]
user.daws90s.uk

[cart]
cart.daws90s.uk

[shipping]
shipping.daws90s.uk

[payment]
payment.daws90s.uk

[frontend]
frontend.daws90s.uk